// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/register": {
            "post": {
                "description": "Register new user account",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Register user",
                "parameters": [{
                    "description": "User credentials",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/auth/login": {
            "post": {
                "description": "Login and receive JWT token",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "User login",
                "parameters": [{
                    "description": "Login credentials",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Logout (client-side token removal for JWT)",
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "User logout",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/password/reset": {
            "post": {
                "description": "Request password reset email",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Password reset",
                "parameters": [{
                    "description": "Email",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/password/change": {
            "post": {
                "description": "Change user password",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Change password",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "description": "Password data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/profile": {
            "get": {
                "description": "Get current user profile",
                "produces": ["application/json"],
                "tags": ["profile"],
                "summary": "Get profile",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            },
            "put": {
                "description": "Update user profile",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["profile"],
                "summary": "Update profile",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "description": "Profile data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/profile/stats": {
            "get": {
                "description": "Get user stats and progress",
                "produces": ["application/json"],
                "tags": ["profile"],
                "summary": "Get profile stats",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/lectures": {
            "get": {
                "description": "List all lectures with optional filters",
                "produces": ["application/json"],
                "tags": ["lectures"],
                "summary": "List lectures",
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/lectures/{id}": {
            "get": {
                "description": "Get lecture by ID",
                "produces": ["application/json"],
                "tags": ["lectures"],
                "summary": "Get lecture",
                "parameters": [{
                    "type": "integer",
                    "description": "Lecture ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/lectures/{id}/complete": {
            "post": {
                "description": "Mark lecture as completed/studied",
                "produces": ["application/json"],
                "tags": ["lectures"],
                "summary": "Complete lecture",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Lecture ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/lectures/{id}/notes": {
            "get": {
                "description": "Get user notes for lecture",
                "produces": ["application/json"],
                "tags": ["notes"],
                "summary": "Get lecture notes",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Lecture ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            },
            "post": {
                "description": "Create note for lecture",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["notes"],
                "summary": "Create lecture note",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Lecture ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                },{
                    "description": "Note content",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/tasks": {
            "get": {
                "description": "List all tasks with optional filters",
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "List tasks",
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/tasks/{id}": {
            "get": {
                "description": "Get task by ID",
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "Get task",
                "parameters": [{
                    "type": "integer",
                    "description": "Task ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/tasks/{id}/solve": {
            "post": {
                "description": "Submit solution for task",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "Submit solution",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Task ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                },{
                    "description": "Solution data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/tasks/{id}/solutions": {
            "get": {
                "description": "Get solution history for task",
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "Get task solutions",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Task ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/tasks/{id}/status": {
            "put": {
                "description": "Update task status",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "Update task status",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Task ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                },{
                    "description": "Status",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/solutions": {
            "get": {
                "description": "List all user solution attempts",
                "produces": ["application/json"],
                "tags": ["solutions"],
                "summary": "List solutions",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/solutions/{id}": {
            "get": {
                "description": "Get specific solution attempt",
                "produces": ["application/json"],
                "tags": ["solutions"],
                "summary": "Get solution",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Solution ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            },
            "put": {
                "description": "Update solution attempt",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["solutions"],
                "summary": "Update solution",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Solution ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                },{
                    "description": "Solution data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            },
            "delete": {
                "description": "Delete solution attempt",
                "produces": ["application/json"],
                "tags": ["solutions"],
                "summary": "Delete solution",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Solution ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/topics": {
            "get": {
                "description": "List all topics",
                "produces": ["application/json"],
                "tags": ["topics"],
                "summary": "List topics",
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/topics/tree": {
            "get": {
                "description": "Get topics in hierarchical tree structure",
                "produces": ["application/json"],
                "tags": ["topics"],
                "summary": "Get topics tree",
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/topics/{id}": {
            "get": {
                "description": "Get topic by ID",
                "produces": ["application/json"],
                "tags": ["topics"],
                "summary": "Get topic",
                "parameters": [{
                    "type": "integer",
                    "description": "Topic ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/professor-chat": {
            "post": {
                "description": "Ask AI professor a question",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["professor-chat"],
                "summary": "Ask professor",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "description": "Question",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/professor-chat/history": {
            "get": {
                "description": "Get chat history with AI professor",
                "produces": ["application/json"],
                "tags": ["professor-chat"],
                "summary": "Get chat history",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/professor-chat/{id}": {
            "get": {
                "description": "Get specific chat message",
                "produces": ["application/json"],
                "tags": ["professor-chat"],
                "summary": "Get chat message",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Message ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/notifications": {
            "get": {
                "description": "Get all user notifications",
                "produces": ["application/json"],
                "tags": ["notifications"],
                "summary": "List notifications",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/notifications/{id}/read": {
            "put": {
                "description": "Mark notification as read",
                "produces": ["application/json"],
                "tags": ["notifications"],
                "summary": "Mark notification read",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Notification ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/history/tasks": {
            "get": {
                "description": "Get user task history",
                "produces": ["application/json"],
                "tags": ["history"],
                "summary": "Task history",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/history/lectures": {
            "get": {
                "description": "Get user lecture history",
                "produces": ["application/json"],
                "tags": ["history"],
                "summary": "Lecture history",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/history/profile": {
            "get": {
                "description": "Get user activity log",
                "produces": ["application/json"],
                "tags": ["history"],
                "summary": "Profile history",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/leaderboard": {
            "get": {
                "description": "Get user leaderboard",
                "produces": ["application/json"],
                "tags": ["leaderboard"],
                "summary": "Leaderboard",
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/achievements": {
            "get": {
                "description": "Get user achievements",
                "produces": ["application/json"],
                "tags": ["achievements"],
                "summary": "Get achievements",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/admin": {
            "get": {
                "description": "Admin dashboard with stats",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Admin dashboard",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/admin/logs": {
            "get": {
                "description": "View system logs",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Admin logs",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/admin/lectures": {
            "get": {
                "description": "Admin lectures list",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Admin lectures",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            },
            "post": {
                "description": "Create new lecture",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Create lecture",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "description": "Lecture data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/admin/lectures/{id}": {
            "put": {
                "description": "Update lecture",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Update lecture",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Lecture ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                },{
                    "description": "Lecture data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            },
            "delete": {
                "description": "Delete lecture",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Delete lecture",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Lecture ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/admin/tasks": {
            "get": {
                "description": "Admin tasks list",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Admin tasks",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            },
            "post": {
                "description": "Create new task",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Create task",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "description": "Task data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/admin/tasks/{id}": {
            "put": {
                "description": "Update task",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Update task",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Task ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                },{
                    "description": "Task data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            },
            "delete": {
                "description": "Delete task",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Delete task",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Task ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/admin/topics": {
            "get": {
                "description": "Admin topics list",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Admin topics",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            },
            "post": {
                "description": "Create new topic",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Create topic",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "description": "Topic data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/admin/topics/{id}": {
            "put": {
                "description": "Update topic",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Update topic",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Topic ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                },{
                    "description": "Topic data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            },
            "delete": {
                "description": "Delete topic",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Delete topic",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "Topic ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/admin/users": {
            "get": {
                "description": "List all users",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "List users",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/admin/users/{id}": {
            "get": {
                "description": "Get user by ID",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Get user",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "User ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            },
            "put": {
                "description": "Update user",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Update user",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "User ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                },{
                    "description": "User data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            },
            "delete": {
                "description": "Delete user",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Delete user",
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "type": "integer",
                    "description": "User ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/ping": {
            "get": {
                "description": "Server status check",
                "produces": ["application/json"],
                "tags": ["technical"],
                "summary": "Ping",
                "responses": {"200": {"description": "OK"}}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Bearer token authentication. Format: Bearer {token}"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "CoolPhy API",
	Description:      "Backend API for educational platform - lectures, tasks, topics, auth, AI professor",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
